### ISSUE TITLE
`EventCollectionNftTransferred` field of callback response is not correct in the official Japanese docs.

### ISSUE THREAD

**Issue by YuheiNakasaka** [line/line-blockchain-developers-sdk-js#109]
I found some wrong information about the field of `EventCollectionNftTransferred` in the Japanese official docs only. `tokenId` in EventCollectionNftTransferred is needed to change to `tokenIds`. In docs of English/한국어 it seems correct.

[GET /v1/item-tokens/{contractId}/fungibles/thumbnail/{request-id}/status](https://docs-blockchain.line.biz/ja/api-guide/Callback-Response#eventcollectionnfttransferred)

<img width="586" alt="スクリーンショット 2023-03-16 12 53 18" src="https://user-images.githubusercontent.com/1421093/225510135-07e9355b-b795-4196-89dc-5656d76e92ab.png">

**Comment by ryukato** [comment]
Oops, sorry that mistake. I will fix it soon.

**Comment by ryukato** [comment]
Sorry late fix, but we have patched the issue. 
https://docs-blockchain.line.biz/ja/api-guide/Callback-Response#eventcollectionnfttransferred
