### ISSUE TITLE
The return type of a function that returns the balance of a specific TokenType NFT owned by a user is incorrect.

### ISSUE THREAD

**Issue by thanaism** [line/line-blockchain-developers-sdk-js#116]
The return type of a function that returns the balance of a specific TokenType NFT owned by a user is incorrect.

Code location:
https://github.com/line/line-blockchain-developers-sdk-js/blob/89e1f827390a681a43c191822f95df3734370f1f/lib/http-client-base.ts#L756

The current code returns the same return type as that of the entire NFT balance owned by the user, but according to the API documentation below, it should return a list of TokenIndex with their corresponding metadata.
https://docs-blockchain.line.biz/en/api-guide/category-users/retrieve#v1-users-userId-item-tokens-contractId-non-fungibles-tokenType-get

**Comment by thanaism** [comment]
I'm not certain, but I think the `TokenIndex` type definition in the same file should be used instead.

**Comment by ryukato** [comment]
Thank you report this issue and I am really sorry for late catch up this issue.
Yes that's totally my bad, the return type has to be `TokenIndex`, I will fix it and patch soon.

**Comment by ryukato** [comment]
PTAL #120
