### ISSUE TITLE
A feature or way to test proxy setting multiple times in single account

### ISSUE THREAD

**Issue by YuheiNakasaka** [line/line-blockchain-developers-sdk-js#130]
## Summary
I am currently implementing codes to set up a proxy setting in order to obtain service tokens and item tokens management permissions following [this documentation](https://docs-blockchain.line.biz/sample-services/finschia-cinema#3-set-up-the-proxy).

But once proxy settings have been completed with single account, I think that there is no way to verify the proxy settings flow again.  Is there a way to reset a proxy setting once it has been completed?  Or how can I test a proxy setting flow multiple times in single LINE account?

And the similar problem occurs in checking user flow for wallet registration.

## Problem Definition

* Why do we need this feature?
This feature is essential to make testings of a proxy setting using the same account more convenient.

## Proposal
To provide a function or document an alternative method for verifying the user flow of a proxy setting multiple times for a single account.

## Check-list
- [x] Not duplicate issue

(At least, I understand that this is a difficult function as we are using blockchain but I want to know a way if there are good ideas.)

**Comment by yeojin-dev** [comment]
Sorry, but we don't have such a feature and don't have any plans to support a requirement like yours.
