### ISSUE TITLE
There are no functions of GetProxy(service,item) 

### ISSUE THREAD

**Issue by KIM-KOOKHYUN** [line/line-blockchain-developers-sdk-js#41]
## Summary
There are no functions of GetProxy(service,item) 
## Problem Definition
There are no functions of GetProxy(service,item) 
- https://docs-blockchain-beta.line-beta.biz/api-guide/category-users/retrieve#v1-users-userId-item-tokens-contractId-proxy-get
- https://docs-blockchain-beta.line-beta.biz/api-guide/category-users/retrieve#v1-users-userId-service-tokens-contractId-proxy-get

## Proposal
Please , implement GetProxy(service,item) 

## Check-list
- [ O] Not duplicate issue

**Comment by ryukato** [comment]
PTAL #45 .
