### ISSUE TITLE
When parse trasaction result with MessageType : collection/MsgTransferNFTFrom , transferredNonFungibleTokens object is empty

### ISSUE THREAD

**Issue by KIM-KOOKHYUN** [line/line-blockchain-developers-sdk-js#43]
### Default information
* lbd-sdk-js version: `e.g. 1.0.0`
* nodeJs version: `e.g. v10.x.x.`
* module-type(specify `type` value in `package.json`): `e.g. commonJs`

### Description of the bug
- Problem
When parse trasaction result with MessageType : collection/MsgTransferNFTFrom , transferredNonFungibleTokens object is empty. 

- Related api function
   - batchTransferNonFungibleTokenOfUser
   - transferNonFungibleTokenOfUser

- Parsing Result
`{
  "height": 15096922,
  "txHash": "B1DAE72B0BA6B0A3AE774786D394AC0395DF2B55EEC9D9126166F7F9E5DAD6C6",
  "from": "tlink1mpurtwj7jmhkypyuft39r7vwpn888fdgskfzd5",
  "proxy": "tlink14vvjtkr39ssmy9qrhv7egrxw8kg5ylpj6l07r8",
  "transferredNonFungibleTokens": []
}`

#### Example codes
Please put the example code where you find the bug

#### Error logs
Please add error logs from the bug

### Anything else we need to know
The value of logs is empty on trasaction result below 
`{
  "responseTime": 1650522902445,
  "statusCode": 1000,
  "statusMessage": "Success",
  "responseData": {
    "height": 15096922,
    "txhash": "B1DAE72B0BA6B0A3AE774786D394AC0395DF2B55EEC9D9126166F7F9E5DAD6C6",
    "codespace": "collection",
    "code": 23,
    "index": 0,
    "data": "",
    "logs": [],
    "info": "",
    "gasWanted": 920000,
    "gasUsed": 38880,
    "tx": {
      "type": "cosmos-sdk/StdTx",
      "value": {
        "msg": [
          {
            "type": "collection/MsgTransferNFTFrom",
            "value": {
              "proxy": "tlink14vvjtkr39ssmy9qrhv7egrxw8kg5ylpj6l07r8",
              "contractId": "ae35e8f6",
              "from": "tlink1mpurtwj7jmhkypyuft39r7vwpn888fdgskfzd5",
              "to": "tlink1mpurtwj7jmhkypyuft39r7vwpn888fdgskfzd5",
              "tokenIds": [
                "1000000400000001"
              ]
            }
          }
        ],
        "fee": {
          "gas": 920000,
          "amount": []
        },
        "memo": "",
        "signatures": [
          {
            "pubKey": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "A86A0Z5qNq7/ODwCNIsk3y0u4vr96mLHRcaZ6mJHueVg"
            },
            "signature": "XPf5hR0Mj7EqNgipTO7JtsRL3YwLoOQr+cqFPo9jadpbGX1kyRkKCmFt8G3QCJu9JI9v6WVAWDRtxKsmAucWzA=="
          }
        ]
      }
    },
    "timestamp": 1650522847000
  }
}`

**Comment by ryukato** [comment]
It has empty `transferredNonFungibleTokens` because it has been failed by [code - 23](https://docs-blockchain.line.biz/api-guide/Callback-Response#codespace-and-code), which is `Token is being not owned.`. That means from addres - tlink1mpurtwj7jmhkypyuft39r7vwpn888fdgskfzd5` is not owner of the token.

But this issue lets me think about a sort of improvement of `TxResultMessage` like below.

```
abstract class TxResultMessage {
  ...
  readonly txResultType: TxResultType,
  code: Number,
  codeDescription: String?, // this is detail description of failure
}

enum TxResultType {
  SUCCESS,  FAILED
}
```

HDYT?

**Comment by ryukato** [comment]
PTAL #44
