### ISSUE TITLE
Wrong api path in the official docs

### ISSUE THREAD

**Issue by YuheiNakasaka** [line/line-blockchain-developers-sdk-js#55]
My apologies if you have already noticed this. But I found some wrong information about the api path in the official docs. `/thumbnail` is needed to change to `/thumbnails`.

- [GET /v1/item-tokens/{contractId}/fungibles/thumbnail/{request-id}/status](https://docs.blockchain.line.me/ja/api-guide/category-item-tokens/retrieve#v1-item-tokens-contractId-fungibles-thumbnail-request-id-status-get)
- [PUT /v1/item-tokens/{contractId}/fungibles/thumbnail](https://docs.blockchain.line.me/ja/api-guide/category-item-tokens/update#v1-item-tokens-contractId-fungibles-thumbnail-put)
- [GET /v1/item-tokens/{contractId}/non-fungibles/thumbnail/{request-id}/status](https://docs.blockchain.line.me/ja/api-guide/category-item-tokens/retrieve#v1-item-tokens-contractId-non-fungibles-thumbnail-request-id-status-get)
- [PUT /v1/item-tokens/{contractId}/non-fungibles/thumbnail](https://docs.blockchain.line.me/ja/api-guide/category-item-tokens/update#v1-item-tokens-contractId-non-fungibles-thumbnail-put)

**Comment by ryukato** [comment]
~Oops sorry about that, I will check and fix them. Thank you.~
Sorry again, the document has been fixed. So I closed this issue. Thank you.
