### ISSUE TITLE
api nonFungibleTokens always sort asc

### ISSUE THREAD

**Issue by ducnh-wano** [line/line-blockchain-developers-sdk-js#58]
I m using api nonFungibleTokens but all the request i used with orderBy: "desc" allways returned the incorrect list with sort asc as default. As i see the docs, it says "sort by token type. Sorting method can be selected with this attribute. Select one from below.
"desc": Descending order (default)
"asc": Ascending order
" but all the time the request i send, it always sort asc though i passed orderBy: "desc" in query params

**Comment by ryukato** [comment]
I appreciate if you let us know which API is and all the parameters you attached.

**Comment by ducnh-wano** [comment]
const { HttpClient } = require("@line/lbd-sdk-js");

const client = new HttpClient(
  "https://test-api.blockchain.line.me",
  "",
  ""
);
  const x = await client.nonFungibleTokens("ee3955c8", {
    page: 1,
    limit: 10,
    orderBy: "desc",
  });
  console.log(x);
  i am using this api, about two weeks ago it worked correctly but now it always sort by asc
  
  here is response 
  [
    {
      tokenType: '10000001',
      name: 'TestContent',
      meta: '',
      createdAt: 1656320445166,
      totalSupply: '15',
      totalMint: '15',
      totalBurn: '0'
    },
    {
      tokenType: '10000002',
      name: 'TestContent2',
      meta: '',
      createdAt: 1656557665267,
      totalSupply: '18',
      totalMint: '18',
      totalBurn: '0'
    },
    {
      tokenType: '10000003',
      name: 'testCreate',
      meta: '',
      createdAt: 1656917294337,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '10000004',
      name: 'Token',
      meta: '',
      createdAt: 1657003744522,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '10000005',
      name: 'Token',
      meta: '',
      createdAt: 1657003746840,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '10000006',
      name: 'Token',
      meta: '',
      createdAt: 1657073196204,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '10000007',
      name: 'Token',
      meta: '',
      createdAt: 1657073212435,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '10000008',
      name: 'Token',
      meta: '',
      createdAt: 1657073254090,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '10000009',
      name: 'Token',
      meta: '',
      createdAt: 1657074229985,
      totalSupply: '0',
      totalMint: '0',
      totalBurn: '0'
    },
    {
      tokenType: '1000000a',
      name: 'testCreate',
      meta: '',
      createdAt: 1657616012851,
      totalSupply: '30',
      totalMint: '30',
      totalBurn: '0'
    }
  ]

**Comment by ducnh-wano** [comment]
As you can see it started from 10000001

**Comment by ryukato** [comment]
Oh yes, I can see what problem is. I am sorry for the bug. I checked situation and will figure out what causes it and let you know after fix it. I can tell you we can fix it within next week.

Thank you for your help.

**Comment by ducnh-wano** [comment]
Did you fix it ?

**Comment by ryukato** [comment]
~Sorry for late answer, yes it has been fixed. I appreciate if you check and let us know if have any issue.~
~I will close this issue but can be re-opened if you have same issue again.~ 

I need to check again, open-api looks fixed though. let me double-check. Sorry for confusion.

**Comment by ryukato** [comment]
I checked again and it looks working fine. please refer to below screen-shots. Please let us know if you still have a problem. 
### query non-fungible token-types with asc
![image](https://user-images.githubusercontent.com/1740710/188545544-debe8cc8-9baa-49bb-9592-d4ada3764568.png)

### query non-fungible token-types with desc
![image](https://user-images.githubusercontent.com/1740710/188545659-8f357c48-80d4-426e-b5f5-b8462572a9ea.png)
