### ISSUE TITLE
url attribute must be optional type

### ISSUE THREAD

**Issue by yeojin-dev** [line/line-blockchain-developers-sdk-js#60]
### Default information
* lbd-sdk-js version: `1.3.0`
* nodeJs version: `v16.17.0`
* module-type(specify `type` value in `package.json`): `commonJs`

### Description of the bug
According to the API document, url attribute in response must be optional type. However, the code is not optional. I think this needs to be corrected.

#### Related documents
* https://docs-blockchain.line.biz/ko/api-guide/category-item-tokens/retrieve#v1-item-tokens-contractId-non-fungibles-thumbnails-request-id-status-get
* https://docs-blockchain.line.biz/ko/api-guide/category-item-tokens/retrieve#v1-item-tokens-contractId-non-fungibles-media-resources-request-id-status-get
* https://docs-blockchain.line.biz/ko/api-guide/category-item-tokens/retrieve#v1-item-tokens-contractId-fungibles-thumbnails-request-id-status-get
* https://docs-blockchain.line.biz/ko/api-guide/category-item-tokens/retrieve#v1-item-tokens-contractId-fungibles-media-resources-request-id-status-get

#### Example codes
https://github.com/line/line-blockchain-developers-sdk-js/blob/47eea13a1fd65f93a688c8accc670663dff1d5d8/lib/response.ts#L74-L91

**Comment by ryukato** [comment]
I close this issue because this has been fixed by #61 and the patch will be released soon.
