### ISSUE TITLE
How can I convert walletAddress to lineUserId

### ISSUE THREAD

**Issue by ducnh-wano** [line/line-blockchain-developers-sdk-js#65]
I want to convert walletAddress to lineUserId
ex: tlink1fr9mpexk5yq3hu6jc0npajfsa0x7tl427fuveq => abc...

**Comment by ryukato** [comment]
Sorry but we don't have such API and any plan to support the requirement like yours.
But I guess you can get user's ID(UID) via [Get user profile API](https://developers.line.biz/en/reference/line-login/#get-user-profile).

So if you have any more question about getting lineUserId, then please take a look at below document.
* [LINE Login](https://developers.line.biz/en/reference/line-login/)

I will close this issue.
