### ISSUE TITLE
imgUri is unnecessary

### ISSUE THREAD

**Issue by yeojin-dev** [line/line-blockchain-developers-sdk-js#66]
### Default information
* lbd-sdk-js version: `1.3.0`
* nodeJs version: `v16.17.0`
* module-type(specify `type` value in `package.json`): `commonJs`

### Description of the bug
According to the API document, imgUri in IssueServiceTokenRequest is unnecessary.

#### Related documents
* https://docs-blockchain.line.biz/api-guide/category-service-tokens#v1-service-tokens-post

#### Example codes
https://github.com/line/line-blockchain-developers-sdk-js/blob/1288973f079b347f9550c547dcb8f4150642ea07/lib/request.ts#L19-L57

**Comment by ryukato** [comment]
this issue has been fixed by #67, and will be released by next publishing.
