### ISSUE TITLE
When do you update sdk to v2?

### ISSUE THREAD

**Issue by ducnh-wano** [line/line-blockchain-developers-sdk-js#93]
Recently i've been known that line blockchain upgraded some api to new version.
For instance: https://docs.blockchain.line.me/ja/api-guide/category-transactions
But when i check in node_modules of sdk, it doesnt update, so i really appreciate if you can update js-sdk fast as possible.
Thank you for your support.

**Comment by ryukato** [comment]
Yo! it has been released! Thank you for waiting. 
https://www.npmjs.com/package/@line/lbd-sdk-js
