### ISSUE TITLE
When typecasting to EventCollectionNftIssued, Set Type variables of objects are returned as Array Type variables.

### ISSUE THREAD

**Issue by KIM-KOOKHYUN** [line/line-blockchain-developers-sdk-js#94]
### Default information
* lbd-sdk-js version: 1.4.0
* nodeJs version: `e.g. v10.x.x.`
* module-type(specify `type` value in `package.json`): `e.g. commonJs`

### Description of the bug

When typecasting to EventCollectionNftIssued, Set Type variables of objects are returned as Array Type variables.

#### Example codes

var txEvent1 : EventCollectionNftIssued = responseV2.responseData.events[0]

// If you see txEvent1 via Debugging, tokenAttributes type is Array

#### Error logs
Please add error logs from the bug

### Anything else we need to know

**Comment by xymz** [comment]
resolved in https://github.com/line/line-blockchain-developers-sdk-js/pull/97
